import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "../provider";
import { AppBarUser } from "../components/AppBarUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Provider>
     

      <body className="min-w-screen min-h-screen bg-[#ebe6e6]">
      <AppBarUser/>
        {children}
        </body>
      </Provider>
    </html>
  );
}
